universe   = vanilla
executable = 10GeV.sh
arguments  = $(ProcId)

output     = 10GeV_log/$(ProcId).out
error      = 10GeV_log/$(ProcId).err
log        = 10GeV_log/$(ProcId).log

request_memory = 3 GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /d0/scratch/kyhwang/WorkSpace/DRC/SEVERANCE/Mar2023/122mm/install/bin, \
					   /d0/scratch/kyhwang/WorkSpace/DRC/SEVERANCE/Mar2023/122mm/install/lib, \
					   /d0/scratch/kyhwang/WorkSpace/DRC/SEVERANCE/Mar2023/122mm/install/init.mac, \
					   /d0/scratch/kyhwang/WorkSpace/DRC/SEVERANCE/Mar2023/122mm/install/10GeV.mac

queue 500
