#This macro can not be executed standalone

/DRsim/action/useHepMC False
/DRsim/action/useCalib False

/vis/disable
/run/numberOfThreads 1
/run/initialize
/run/verbose 1

/DRsim/generator/theta 1.5
/DRsim/generator/phi 1.

/DRsim/generator/x0 -1.3093
/DRsim/generator/y0 -0.87275
/DRsim/generator/z0 -50

/DRsim/generator/randx 10
/DRsim/generator/randy 10
/DRsim/generator/randz 0

/gun/particle e-
/gun/energy 20 GeV
/run/beamOn 2

