#This macro can not be executed standalone

/DRsim/action/useHepMC False
/DRsim/action/useCalib False

/vis/disable
/run/numberOfThreads 1
/run/initialize
/run/verbose 1

/DRsim/generator/theta 0.
/DRsim/generator/phi 0.

/DRsim/generator/x0 -2.7
/DRsim/generator/y0 -3.45
/DRsim/generator/z0 0

/DRsim/generator/randx 10
/DRsim/generator/randy 10
/DRsim/generator/randz 0

/gun/particle e-
/gun/energy 4 GeV
/run/beamOn 500


